import type { StateCreator } from 'zustand';
import type { AppStore, AudioSlice } from './types';
import { initialPitch, initialBass, initialGuitar, initialPiano } from './types';

export const createAudioSlice: StateCreator<AppStore, [], [], AudioSlice> = (set) => ({
  isPassthroughActive: false,
  isRecording: false,
  inputLevel: 0,
  latencyMs: 0,
  inputGain: 1.0,
  outputVolume: 0.8,
  currentInstrument: 'drums',
  loops: [],
  error: null,
  pitch: initialPitch,
  instrumentMode: 'drums',
  currentDrum: null,
  bass: initialBass,
  guitar: initialGuitar,
  piano: initialPiano,

  setPassthroughActive: (active) => set({ isPassthroughActive: active }),
  setRecording: (recording) => set({ isRecording: recording }),
  setInputLevel: (level) => set({ inputLevel: Math.max(0, Math.min(1, level)) }),
  setLatency: (latencyMs) => set({ latencyMs }),
  setPitch: (pitch) => set({ pitch }),
  setInstrumentMode: (mode) => set({ instrumentMode: mode }),
  setCurrentDrum: (drum) => set({ currentDrum: drum }),
  setBass: (bass) => set((state) => ({ bass: { ...state.bass, ...bass } })),
  setBassSynthType: (synthType) => set((state) => ({ bass: { ...state.bass, synthType } })),
  setBassStyle: (style) => set((state) => ({ bass: { ...state.bass, style } })),
  setRealisticBassStyle: (style) => set((state) => ({ bass: { ...state.bass, realisticStyle: style } })),
  setGuitar: (guitar) => set((state) => ({ guitar: { ...state.guitar, ...guitar } })),
  setGuitarSynthType: (synthType) => set((state) => ({ guitar: { ...state.guitar, synthType } })),
  setGuitarStyle: (style) => set((state) => ({ guitar: { ...state.guitar, style } })),
  setRealisticGuitarStyle: (style) => set((state) => ({ guitar: { ...state.guitar, realisticStyle: style } })),
  setPiano: (piano) => set((state) => ({ piano: { ...state.piano, ...piano } })),
  setPianoSynthType: (synthType) => set((state) => ({ piano: { ...state.piano, synthType } })),
  setPianoStyle: (style) => set((state) => ({ piano: { ...state.piano, style } })),
  setRealisticPianoStyle: (style) => set((state) => ({ piano: { ...state.piano, realisticStyle: style } })),
  setInputGain: (gain) => set({ inputGain: Math.max(0, Math.min(2, gain)) }),
  setOutputVolume: (volume) => set({ outputVolume: Math.max(0, Math.min(1, volume)) }),
  setCurrentInstrument: (instrument) => set({ currentInstrument: instrument }),
  addLoop: (loop) => set((state) => ({ loops: [...state.loops, loop] })),
  removeLoop: (id) => set((state) => ({ loops: state.loops.filter((loop) => loop.id !== id) })),
  updateLoop: (id, updates) => set((state) => ({
    loops: state.loops.map((loop) => loop.id === id ? { ...loop, ...updates } : loop),
  })),
  clearLoops: () => set({ loops: [] }),
  setError: (error) => set({ error }),
  clearError: () => set({ error: null }),
});
